### ISSUE TITLE
getting 500 Internel Server Error all the time

### ISSUE THREAD

**Issue by Howard1989** [gooichi/foursquare-ios-api#10]
Hi  my friend
        I followed your tutorial and could use my own URL and clientID successfully login to foursquare, but everytime I click allow, there pop up a error page said 500 Internel Server Error.
on the website it says that's wrong page with database problem, but I think the app is supposed to lead me back to it, however it isn't.
       I wonder I missed something or this is just some techinical errors there which is shouldn't.

Thank you !
Howard

**Comment by baztokyo** [comment]
Does your problem always (now) occur? We have checked it. For now no error.

> on the website it says that's wrong page with database problem, but I think the app is supposed to lead me back to it, however it isn't.

If the error occurs on the website (Safari), unfortunately, the app cannot lead you back to it.
