### ISSUE TITLE
URL callback issue

### ISSUE THREAD

**Issue by pixelrevision** [gooichi/foursquare-ios-api#12]
Not sure if this is an actual issue or not but it could be problematic based on the input on the site.  At the moment the site only allows you to put in callback urls as:
type://value
I was having issues with line 104 of BZFoursquare where it was always returning no not recognizing the full path as a prefix:

```
if (![[url absoluteString] hasPrefix:callbackURL_]) {
    return NO;
}
```

Adding a category and changing to use this fixes it for me:

```
NSString *urlString = [url absoluteString];
if([urlString rangeOfString:callbackURL_ options:NSCaseInsensitiveSearch].location == NSNotFound){
    return NO;
} 
```

Anyway something to have here in case anyone has issues.

**Comment by baztokyo** [comment]
Please try 1.1.1.
