### ISSUE TITLE
How to get Photo details 

### ISSUE THREAD

**Issue by macIndian** [gooichi/foursquare-ios-api#16]
HI, 
i had  add photo  with this demo application but now i want to get uploaded  photo details with id ,
i had tray with 
https://api.foursquare.com/v2/photos/PHOTO_ID
but i didnt get any response 

this is URL which i am testing , 

https:/api.foursquare.com/v2/photos?oauth_token=APV1DJMP0MX3KX1F2HGWJ0XUYEHNHVWDENVIEA5BOY33TGSE&PHOTO_ID=51935629498e9b106a00f418&v=20111119&locale=en

Thanks ,

**Comment by baztokyo** [comment]
PHOTO_ID is a part of a url path. Please try the following url:

 https:/api.foursquare.com/v2/photos/51935629498e9b106a00f418?oauth_token=APV1DJMP0MX3KX1F2HGWJ0XUYEHNHVWDENVIEA5BOY33TGSE&v=20111119&locale=en

For more details, please refer to the following page:

 https://developer.foursquare.com/docs/photos/photos
