### ISSUE TITLE
Implicit conversion of a non-Objective-C

### ISSUE THREAD

**Issue by ojoaldato** [gooichi/foursquare-ios-api#28]
Hi!

I have been trying to add this library to a project and faced the next problem when initializing the object:
        self.foursquare = [[BZFoursquare alloc] initWithClientID:kClientID callbackURL:kCallbackURL];

This is the bug that pops up: "Implicit conversion of a non-Objective-C pointer type char\* to NSString is disallowed with ARC".

Has anyone faced a similar problem? I have been trying so solve with without no success.

**Comment by baztokyo** [comment]
Please make sure that the arguments (kClientID and kCallbackURL) are NSString.
