### ISSUE TITLE
Question: Xcode User-Defined Build Settings

### ISSUE THREAD

**Issue by markdorison** [gooichi/foursquare-ios-api#4]
I see in the FSQDemo sample project that the user-defined build settings created for the target are referenced in FSQMasterViewController.m as seen below:

```
#define kClientID       FOURSQUARE_CLIENT_ID
#define kCallbackURL    FOURSQUARE_CALLBACK_URL
```

When I try to do this in my own project, I get an error at compile time stating 'Use of undeclared identifier FOURSQUARE_CLIENT_ID'. Do I need to do something else to gain access to those user-defined build settings?

**Comment by baztokyo** [comment]
Please replace YOUR_CLIENT_ID in Xcode Build Settings with your app's Client ID. (see README.md > Sample Applications.)

**Comment by markdorison** [comment]
@baztokyo: This works fine for me in the sample project but when I try to implement it in my own project it does not seem to recognize the user-defined build setting that I create.

**Comment by baztokyo** [comment]
Please add the following compiler flags to your sources in Xcode Build Phrases > Compile Sources.

 -D'FOURSQUARE_CLIENT_ID=@"$(FOURSQUARE_CLIENT_ID)"' -D'FOURSQUARE_CALLBACK_URL=@"$(FOURSQUARE_CALLBACK_URL)"'

**Comment by markdorison** [comment]
@baztokyo That worked. Thank you!

**Comment by Gurpartap** [comment]
:+1:

**Comment by antonshevchenko** [comment]
Thanks! :+1:
