### ISSUE TITLE
Missing header file "BZSynthesizeSingleton.h"

### ISSUE THREAD

**Issue by camenre** [gooichi/foursquare-ios-api#5]
When trying to run FSQDemo, it cannot import the header file (missing).

**Comment by rl1987** [comment]
Compiling and running FSQDemo works just fine for me.

**Comment by baztokyo** [comment]
The following files in FSQDemo are not necessary. I removed them, sorry.
- FSQFoursquare.h
- FSQFoursquare.m

**Comment by camenre** [comment]
Worked
