### ISSUE TITLE
userless requests

### ISSUE THREAD

**Issue by Xecutor** [gooichi/foursquare-ios-api#6]
It would be VERY nice to have api for userless requests. Like list of nearby venues.

**Comment by baztokyo** [comment]
I'm sorry for my late reply.
Please try 1.1.0.

**Comment by amontanari** [comment]
Hi, where is correct define secret id for userless request?

**Comment by baztokyo** [comment]
In the sample app we have not defined it.
You need to set secret id (BZFoursquare.clientSecret) dynamically from your app.
